[package]
name = "spin2win"
version = "1.0.0"
authors = []

[addresses]
spin2win = "0x452cda0816d56857bd597bfc7d82cad2da1bfc6197c1eadb2a6476966ac3e9ea"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
