[package]
name = "spin2win"
version = "1.0.0"
authors = []

[addresses]
spin2win = "0x03711cef76324617ae268a5c7502948e0395e1d8b2300653bbe8cf47ff988d4e"
[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git",rev="mainnet",subdir="aptos-move/framework/aptos-framework"}
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git",rev="mainnet",subdir="aptos-move/framework/aptos-token-objects"}
AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git",rev="mainnet",subdir="aptos-move/framework/aptos-token"}

[dev-dependencies]
